import './primitives/a-camera';
import './primitives/a-cursor';
import './primitives/a-curvedimage';
import './primitives/a-gltf-model';
import './primitives/a-image';
import './primitives/a-light';
import './primitives/a-link';
import './primitives/a-obj-model';
import './primitives/a-sky';
import './primitives/a-sound';
// import './primitives/a-text';
import './primitives/a-video';
import './primitives/a-videosphere';
import './primitives/meshPrimitives';
