import { options } from './options';
import * as utils from './utils';
import { NafLogger } from './NafLogger';
import { Schemas } from './Schemas';
import { NetworkEntities } from './NetworkEntities';
import { NetworkConnection } from './NetworkConnection';
import { AdapterFactory } from './adapters/AdapterFactory';

export const NAF = {};
NAF.app = '';
NAF.room = '';
NAF.clientId = '';
NAF.options = options;
NAF.utils = utils;
NAF.log = new NafLogger();
NAF.schemas = new Schemas();
NAF.version = "0.12.2";
NAF.adapters = new AdapterFactory();
NAF.entities = new NetworkEntities();
NAF.connection = new NetworkConnection(NAF.entities);
